font_family      JetBrains Mono
font_size        11.5
window_padding_width 14
confirm_os_window_close 0
enable_audio_bell no
hide_window_decorations yes

# Colours: written by fw13.theme
include ~/.config/fw13/theme/kitty.conf
