"""Setup-time choices the installer asked once: Chromium sign-in keys, Ollama Cloud key, restic backups, login
shell; plus read-only facts about the dotfiles checkout and what the installer set up.

Values live in ~/.config/chezmoi/chezmoi.toml ([data.chromium] / [data.restic] / [data.ollama], the shape
.chezmoi.toml.tmpl renders, plus the optional [data.restic_creds] with S3 keys, which has no prompt and the template
writes back as it is); chezmoi turns them into private_ files. Secrets never go into argv, logs, store.py
or a returned message: status() reports only "set" and a length, restic gets them through env=, and every error
text passes through _redact(). Calls may block (chezmoi, restic, polkit): run them from a worker thread.
"""
import fcntl
import json
import os
import pwd
import re
import shutil
import subprocess
import time
import tomllib

from . import store
from .system import _err, _run

HOME = os.path.expanduser("~")
CONFIG = os.path.join(os.environ.get("XDG_CONFIG_HOME") or os.path.join(HOME, ".config"), "chezmoi",
                      "chezmoi.toml")
CHECKOUT = os.path.join(HOME, ".local/share/fw13-hypr")  # install.sh's own clone (CHECKOUT)
INSTALLER = os.path.join(CHECKOUT, "install.sh")

# Table → keys, in the order .chezmoi.toml.tmpl writes them.
SCHEMA = {"chromium": ("api_key", "client_id", "client_secret"),
          "restic": ("repository", "password"),
          "ollama": ("api_key",),
          "restic_creds": ("aws_access_key_id", "aws_secret_access_key", "aws_default_region")}
# Tables without a prompt: written only while one of their values is set, keys sorted and unaligned (the template's
# `range` over the table), so a re-init renders the same text.
OPTIONAL = ("restic_creds",)
# S3 (AWS, Backblaze B2, Wasabi, R2, MinIO) is the only cloud backend whose keys this page stores; sftp:, rest:
# (user:pass in the URL), rclone: and local paths need none. Native b2:/azure:/gs:/swift: would need keys of their own.
S3_KEYS = ("aws_access_key_id", "aws_secret_access_key", "aws_default_region")
S3_REQUIRED = ("aws_access_key_id", "aws_secret_access_key")
UNSUPPORTED = ("b2:", "azure:", "gs:", "swift:")
NATIVE_KEY_PREFIXES = ("B2_", "AZURE_", "GOOGLE_", "OS_", "ST_")  # their own env keys, if added to the env file by hand

# Values end up unquoted in environment.d / EnvironmentFile lines: no whitespace, quotes, $, `, #, \ or newlines.
VALUE_RE = re.compile(r"[A-Za-z0-9._~:/@+=%,_-]{0,512}")
USERINFO_RE = re.compile(r"(?i)([a-z][a-z0-9+.-]*://)[^/@\s]*@")  # rest:https://user:pass@host/ → rest:https://host/

# Files chezmoi renders from these values. Before one is overwritten or deleted it must still be what chezmoi
# wrote: an env file holds only its template's comment lines (the first is required) and keys; a restic unit
# (static, no header) matches `chezmoi cat` byte for byte. Anything else was edited by hand and is left alone.
T_CHROMIUM = os.path.join(HOME, ".config/environment.d/50-chromium-oauth.conf")
T_OLLAMA = os.path.join(HOME, ".config/environment.d/60-ollama.conf")
T_RESTIC_ENV = os.path.join(HOME, ".config/restic/env")
T_RESTIC_SVC = os.path.join(HOME, ".config/systemd/user/restic-backup.service")
T_RESTIC_TIMER = os.path.join(HOME, ".config/systemd/user/restic-backup.timer")
RESTIC_KEYS = ("RESTIC_REPOSITORY", "RESTIC_PASSWORD",
               "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_DEFAULT_REGION")  # AWS_* only for s3:
CRED_ENV = {k: k.upper() for k in S3_KEYS}  # restic_creds key → env name
ENV_FILES = {T_CHROMIUM: (("# Generated by chezmoi from values in ~/.config/chezmoi/chezmoi.toml",
                           "# Personal OAuth client for Chromium Sync."),
                          ("GOOGLE_API_KEY", "GOOGLE_DEFAULT_CLIENT_ID", "GOOGLE_DEFAULT_CLIENT_SECRET")),
             T_OLLAMA: (("# Ollama Cloud key for OpenCode",), ("OLLAMA_API_KEY",)),
             T_RESTIC_ENV: (("# restic environment — generated by chezmoi",), RESTIC_KEYS)}
TARGETS = {"chromium": (T_CHROMIUM,), "ollama": (T_OLLAMA,),
           "restic": (T_RESTIC_ENV, T_RESTIC_SVC, T_RESTIC_TIMER),  # the unit's restic options follow the repository
           "restic_creds": (T_RESTIC_ENV,)}
PLAIN = {("restic", "repository"), ("restic_creds", "aws_default_region")}  # every other value is a secret
MIN_SECRET = 4  # _redact() masks secrets this long or longer; shorter ones would be unsafe to echo

UNIT, TIMER = "restic-backup.service", "restic-backup.timer"
SHELLS = ("bash", "zsh", "fish")


# --- chezmoi.toml ------------------------------------------------------------

def _read_config():
    """Parsed chezmoi.toml, {} when missing. Raises ValueError on a file this page can't safely rewrite."""
    try:
        with open(CONFIG, "rb") as f:
            data = tomllib.load(f)
    except FileNotFoundError:
        other = [n for n in ("chezmoi.yaml", "chezmoi.yml", "chezmoi.json", "chezmoi.jsonc")
                 if os.path.exists(os.path.join(os.path.dirname(CONFIG), n))]
        if other:
            raise ValueError(f"chezmoi uses {other[0]}; change these values with `chezmoi edit-config`") from None
        return {}
    except tomllib.TOMLDecodeError as e:
        raise ValueError(f"~/.config/chezmoi/chezmoi.toml doesn't parse ({e})") from None
    _check_shape(data)
    return data


def _check_shape(data):
    """Only the tables the template writes, string values only — anything else would be lost on rewrite."""
    extra = [k for k in data if k != "data"]
    tables = data.get("data", {})
    if not isinstance(tables, dict):
        extra.append("data")
        tables = {}
    for t, keys in tables.items():
        if t not in SCHEMA or not isinstance(keys, dict):
            extra.append(f"data.{t}")
            continue
        extra += [f"data.{t}.{k}" for k, v in keys.items() if k not in SCHEMA[t] or not isinstance(v, str)]
    if extra:
        raise ValueError("chezmoi.toml has settings this page doesn't manage (" + ", ".join(extra[:4])
                         + "); change these values with `chezmoi edit-config`")


def _values():
    """{table: {key: value}} with every SCHEMA key present ("" when unset)."""
    tables = _read_config().get("data", {})
    return {t: {k: tables.get(t, {}).get(k, "") for k in keys} for t, keys in SCHEMA.items()}


def _quote(s):
    """TOML basic string. Matches chezmoi's `quote` (Go %q) for everything validate() lets through, and stays
    valid TOML for any older value (control characters as \\uXXXX)."""
    out = []
    for ch in s:
        if ch in '"\\':
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _compact(values):
    """values as chezmoi.toml holds them: an OPTIONAL table keeps only its set keys, and is left out when empty."""
    out = {}
    for t, keys in values.items():
        if t in OPTIONAL:
            keys = {k: v for k, v in keys.items() if v}
            if not keys:
                continue
        out[t] = dict(keys)
    return out


def _render(values):
    """The same text .chezmoi.toml.tmpl produces (column-aligned keys; OPTIONAL tables as its `range` writes them)."""
    lines = []
    for t, keys in SCHEMA.items():
        if t in OPTIONAL:
            set_keys = sorted(k for k in keys if values[t][k])
            if set_keys:
                lines.append(f"[data.{t}]")
                lines += [f"  {k} = {_quote(values[t][k])}" for k in set_keys]
            continue
        lines.append(f"[data.{t}]")
        width = max(len(k) for k in keys) if t != "ollama" else len("repository")  # template's own alignment
        lines += [f"  {k.ljust(width)} = {_quote(values[t][k])}" for k in keys]
    return "\n".join(lines) + "\n"


def _redact(text, values=None):
    """Remove every known secret and URL user:pass@ from a message meant for the page."""
    if values is None:
        try:
            values = _values()
        except (OSError, ValueError):
            values = {}
    if any(0 < len(v) < MIN_SECRET for t, keys in values.items() for k, v in keys.items() if (t, k) not in PLAIN):
        return "Details hidden (a key is too short to mask in messages)"
    secrets = sorted((v for t in values.values() for v in t.values() if len(v) >= MIN_SECRET), key=len,
                     reverse=True)
    for s in secrets:
        text = text.replace(s, "•••")
    return USERINFO_RE.sub(r"\1", text)


def display_repository(repo):
    """The repository without credentials: rest:https://user:pass@host/x → rest:https://host/x."""
    return USERINFO_RE.sub(r"\1", repo)


def validate(value, secret=False):
    """(ok, message). Never repeats the value. A secret is empty or at least MIN_SECRET characters."""
    if secret and 0 < len(value) < MIN_SECRET:
        return False, f"Too short ({MIN_SECRET} characters at least)"
    if VALUE_RE.fullmatch(value):
        return True, ""
    if len(value) > 512:
        return False, "Too long (512 characters at most)"
    return False, "Contains a character that can't be used (spaces, quotes, $ ` # \\ or line breaks)"


def status():
    """{table: {key: {"set": bool, "len": int}}}; restic.repository also has "display". "error" when the file
    can't be read. Never returns a secret."""
    try:
        vals = _values()
        error = ""
    except (OSError, ValueError) as e:
        vals = {t: {k: "" for k in keys} for t, keys in SCHEMA.items()}
        error = _redact(str(e), {})
    out = {t: {k: {"set": bool(v), "len": len(v)} for k, v in keys.items()} for t, keys in vals.items()}
    out["restic"]["repository"]["display"] = display_repository(vals["restic"]["repository"])
    out["restic"]["repository"]["needs"] = restic_needs(vals["restic"]["repository"])
    out["error"] = error
    out["exists"] = os.path.exists(CONFIG)
    return out


def _lock_path():
    run = os.environ.get("XDG_RUNTIME_DIR") or os.path.join(HOME, ".cache")
    os.makedirs(run, exist_ok=True)
    return os.path.join(run, "fw13-setup.lock")


class _Lock:
    """Exclusive lock for a read-modify-write of chezmoi.toml (two Settings actions, or a second window)."""

    def __enter__(self):
        self.fd = os.open(_lock_path(), os.O_CREAT | os.O_RDWR, 0o600)
        deadline = time.monotonic() + 10
        while True:
            try:
                fcntl.flock(self.fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
                return self
            except BlockingIOError:
                if time.monotonic() > deadline:
                    os.close(self.fd)
                    raise TimeoutError("Another change is still being saved — try again") from None
                time.sleep(0.1)

    def __exit__(self, *_):
        fcntl.flock(self.fd, fcntl.LOCK_UN)
        os.close(self.fd)


def _write_atomic(path, text, mode=0o600):
    d = os.path.dirname(path)
    os.makedirs(d, mode=0o700, exist_ok=True)
    tmp = os.path.join(d, f".{os.path.basename(path)}.{os.getpid()}.tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp, mode)
        os.replace(tmp, path)
        dfd = os.open(d, os.O_RDONLY)
        try:
            os.fsync(dfd)
        finally:
            os.close(dfd)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def save(updates):
    """updates: {table: {key: value}}; "" clears a value. (ok, message)."""
    for t, keys in updates.items():
        for k, v in keys.items():
            if t not in SCHEMA or k not in SCHEMA[t]:
                return False, f"Unknown setting {t}.{k}"
            ok, msg = validate(v, (t, k) not in PLAIN)
            if not ok:
                return False, f"{k.replace('_', ' ').capitalize()}: {msg}"
    try:
        with _Lock():
            vals = _values()
            for p in (p for t in updates for p in TARGETS[t] if p in ENV_FILES):
                msg = hand_edit(p)
                if msg:
                    return False, msg
            for t, keys in updates.items():
                vals[t].update(keys)
            text = _render(vals)
            parsed = tomllib.loads(text)  # what chezmoi will read back
            _check_shape(parsed)
            if parsed.get("data") != _compact(vals):
                return False, "Couldn't write chezmoi.toml safely (values didn't read back the same)"
            _write_atomic(CONFIG, text)
    except (OSError, ValueError, TimeoutError, tomllib.TOMLDecodeError) as e:
        return False, _redact(str(e))
    return True, ""


# --- rendered files -----------------------------------------------------------

def chezmoi_bin():
    for c in (shutil.which("chezmoi"), os.path.join(HOME, ".local/share/mise/shims/chezmoi")):
        if c and os.access(c, os.X_OK):
            return c
    return None


def apply_targets(paths, source=None):
    """Render just these files from the user's chezmoi source (no scripts). (ok, message)."""
    exe = chezmoi_bin()
    if not exe:
        return False, "chezmoi isn't installed (mise install chezmoi)"
    cmd = [exe, "apply", "--force", "--no-tty", "--exclude=scripts", "--recursive=false"]
    if source:
        cmd.append(f"--source={source}")
    dirs = []  # chezmoi doesn't create a missing parent of a target: apply those dirs too (just the dir)
    for p in paths:
        d = os.path.dirname(p)
        while d.startswith(HOME + os.sep) and not os.path.isdir(d) and d not in dirs:
            dirs.insert(0, d)
            d = os.path.dirname(d)
    dirs.sort(key=len)
    rc, _out, err = _run(*cmd, "--", *dirs, *paths, timeout=60)
    ok, msg = _err(rc, err, "chezmoi apply")
    if not ok and "not in source state" in (err or ""):
        # The page is newer than the dotfiles chezmoi applies (e.g. a file added since the last update).
        msg = "Your dotfiles are older than this page: run `chezmoi update --init` once, then try again"
    return ok, _redact(msg)


def _short(path):
    return "~/" + os.path.relpath(path, HOME)


def _read_text(path):
    """Content of a plain file, None when missing / a symlink / not a regular file."""
    if os.path.islink(path) or not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read()


def hand_edit(path, source=None):
    """None when `path` is missing or still what chezmoi wrote; else why it must be left alone (a re-render or
    removal would lose what was added by hand)."""
    if not os.path.lexists(path):
        return None
    try:
        text = _read_text(path)
    except OSError as e:
        return f"{_short(path)}: {e.strerror}"
    if text is None:
        return f"{_short(path)} isn't a plain file — edit it yourself"
    if path in ENV_FILES:
        comments, keys = ENV_FILES[path]
        lines = [s.strip() for s in text.splitlines() if s.strip()]
        if not any(s.startswith(comments[0]) for s in lines):
            return f"{_short(path)} wasn't written by chezmoi — edit that file instead"
        extra = [s for s in lines if not (s.startswith(comments) if s.startswith("#")
                                          else s.split("=", 1)[0].strip() in keys)]
        if extra:
            names = sorted({s.split("=", 1)[0].strip() for s in extra if "=" in s and not s.startswith("#")})
            what = ", ".join(names[:3]) if names else "comments"
            return f"{_short(path)} has lines added by hand ({what}) — edit that file instead"
        if path == T_RESTIC_ENV:
            # S3 keys added by hand before [data.restic_creds] existed: a re-render would drop them.
            try:
                creds = _values()["restic_creds"]
            except (OSError, ValueError) as e:
                return _redact(str(e), {})
            want = {CRED_ENV[k]: v for k, v in creds.items() if v}
            have = {s.split("=", 1)[0].strip(): s.split("=", 1)[1].strip() for s in lines
                    if not s.startswith("#") and s.startswith("AWS_") and "=" in s}
            hand = sorted(k for k, v in have.items() if want.get(k) != v)
            if hand:
                return (f"{_short(path)} has keys added by hand ({', '.join(hand[:3])}) — remove those lines, "
                        "then enter the keys here")
        return None
    exe = chezmoi_bin()
    rc, out, _e = _run(exe, "cat", *([f"--source={source}"] if source else []), "--", path, timeout=30) \
        if exe else (127, "", "")
    if rc != 0 or out != text:
        return f"{_short(path)} differs from the dotfiles (changed by hand?) — edit or delete it yourself"
    return None


def remove(table, source=None):
    """Clear a table's values and delete its rendered files (restic: its S3 keys too). (ok, message). Nothing
    happens when one of the files was changed by hand; the timer is turned off only once the values are cleared."""
    files = {}
    for p in TARGETS[table]:
        msg = hand_edit(p, source)  # before save(): once the values are blank chezmoi no longer manages the units
        if msg:
            return False, msg
        if os.path.lexists(p):
            files[p] = _read_text(p)
    clear = {table: {k: "" for k in SCHEMA[table]}}
    if table == "restic":
        clear["restic_creds"] = {k: "" for k in S3_KEYS}
    ok, msg = save(clear)
    if not ok:
        return ok, msg
    if table == "restic" and T_RESTIC_TIMER in files:
        _run("systemctl", "--user", "disable", "--now", TIMER, timeout=20)
    notes = []
    for p, text in files.items():
        try:
            if _read_text(p) != text:
                notes.append(f"{_short(p)} changed meanwhile — left in place")
                continue
            os.unlink(p)
        except OSError as e:
            notes.append(f"{_short(p)}: {e.strerror}")
    _reload_user_manager()
    return (False, "; ".join(notes)) if notes else (True, "")


def set_values(table, values, source=None):
    """Save, then render that table's files. (ok, message). Refused when one of them was changed by hand."""
    for p in TARGETS[table]:
        msg = hand_edit(p, source)
        if msg:
            return False, msg
    ok, msg = save({table: values})
    if not ok:
        return ok, msg
    ok, msg = apply_targets(list(TARGETS[table]), source)
    if ok:
        _reload_user_manager()
    return ok, msg


def set_restic(values, creds, source=None):
    """Save the repository/password and its S3 keys together, then render the env file and the unit. (ok, message).
    values/creds: {key: value}, a missing or "" key keeps its current value; a repository that needs no keys clears
    the stored ones."""
    try:
        cur = _values()
    except (OSError, ValueError) as e:
        return False, _redact(str(e), {})
    repo = values.get("repository") or cur["restic"]["repository"]
    needs = restic_needs(repo)
    if needs is None:
        return False, unsupported_message(repo)
    if needs:
        creds = {k: v for k, v in creds.items() if k in needs and v}
        missing = [k for k in S3_REQUIRED if not (creds.get(k) or cur["restic_creds"][k])]
        if missing:
            return False, "S3 needs an access key ID and a secret access key"
    else:
        creds = {k: "" for k in S3_KEYS}
    for p in TARGETS["restic"]:
        msg = hand_edit(p, source)
        if msg:
            return False, msg
    ok, msg = save({"restic": {k: v for k, v in values.items() if v}, "restic_creds": creds})
    if not ok:
        return ok, msg
    ok, msg = apply_targets(list(TARGETS["restic"]), source)
    if ok:
        _reload_user_manager()
    return ok, msg


def _reload_user_manager():
    """Re-run the user manager's generators: unit files (restic) and environment.d (the Chromium and Ollama keys).
    The manager reads environment.d only when it starts or reloads, and user services (Citadel, WARP…) often keep it
    running across a logout, so without this a re-login still got the old environment."""
    _run("systemctl", "--user", "daemon-reload", timeout=20)


# --- restic ------------------------------------------------------------------

def restic_needs(repo):
    """restic_creds keys this repository uses: S3_KEYS for s3:, () when it needs none, None for a backend whose keys
    this page can't store (native b2:, azure:, gs:, swift:)."""
    if repo.startswith("s3:"):
        return S3_KEYS
    if repo.startswith(UNSUPPORTED):
        return None
    return ()


def unsupported_message(repo):
    if repo.startswith("b2:"):
        return "Use Backblaze's S3 endpoint instead of b2: (s3:https://s3.<region>.backblazeb2.com/<bucket>/fw13)"
    return f"{repo.split(':', 1)[0]}: needs keys this page can't store; use s3: or sftp:"


def restic_env():
    """Environment for a restic run: the rendered env file (with the S3 keys), else chezmoi.toml."""
    env = {}
    try:
        with open(T_RESTIC_ENV, encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip()
    except OSError:
        pass
    if not env.get("RESTIC_REPOSITORY"):
        try:
            v = _values()["restic"]
        except (OSError, ValueError):
            return env
        env.update(RESTIC_REPOSITORY=v["repository"], RESTIC_PASSWORD=v["password"])
        if restic_needs(v["repository"]):
            env.update({CRED_ENV[k]: c for k, c in _values()["restic_creds"].items() if c})
    return env


def _restic(*args, timeout=30):
    """(rc, stdout, stderr) of restic with the repo + password in its environment only."""
    if not shutil.which("restic"):
        return 127, "", "restic is not installed"
    renv = restic_env()
    if not renv.get("RESTIC_REPOSITORY") or not renv.get("RESTIC_PASSWORD"):
        return 1, "", "No repository or password set"
    opts = ["-o", "sftp.args=-oBatchMode=yes -oConnectTimeout=15"] \
        if renv["RESTIC_REPOSITORY"].startswith("sftp:") else []
    # Only the env file's keys, as for the service: none inherited from the session.
    keyed = ("AWS_", *NATIVE_KEY_PREFIXES)
    env = {**{k: v for k, v in os.environ.items() if not k.startswith(keyed)}, **renv, "RESTIC_PROGRESS_FPS": "0"}
    try:
        p = subprocess.run(["restic", *opts, *args], capture_output=True, text=True, env=env,
                           stdin=subprocess.DEVNULL, timeout=timeout)
        return p.returncode, p.stdout, _redact(p.stderr)
    except subprocess.TimeoutExpired:
        return 124, "", "The repository didn't answer in time"
    except OSError as e:
        return 126, "", f"restic: {e.strerror or e}"


def restic_test():
    """(state, message). state: "ok", "missing" (exit 10: run restic_init), "password" (exit 12), "error"."""
    renv = restic_env()
    needs = restic_needs(renv.get("RESTIC_REPOSITORY", ""))
    hint = ""
    if needs is None:
        # A working native setup with its keys added to the env file by hand still gets tested (the service uses
        # them too); without such keys it can't connect, so only the hint is shown.
        hint = unsupported_message(renv["RESTIC_REPOSITORY"])
        if not any(k.startswith(NATIVE_KEY_PREFIXES) for k in renv):
            return "error", hint
    elif needs and not all(renv.get(CRED_ENV[k]) for k in S3_REQUIRED):
        return "error", "S3 needs an access key ID and a secret access key — add them under Change"
    rc, _o, err = _restic("cat", "config")
    if rc == 0:
        rc, _o, err = _restic("snapshots", "--no-lock", "--json", "--latest", "1")
    if rc == 0:
        if hint:
            return "ok", (f"Connected — {hint[0].lower()}{hint[1:]} (keys added by hand are lost when Settings "
                          "rewrites the env file)")
        return "ok", "Connected"
    if rc == 10:
        return "missing", "No repository there yet — Initialise creates it"
    if rc == 12:
        return "password", "Wrong password for this repository"
    return "error", _err(rc or 1, err, "Connecting to the repository")[1]


def restic_init():
    rc, _o, err = _restic("init", timeout=120)
    return _err(rc, err, "Initialising the repository")


def backup_now():
    """Start the backup service and return at once; poll backup_state() for the result."""
    return _err(*_run("systemctl", "--user", "start", "--no-block", UNIT, timeout=20)[0::2], "Starting the backup")


def backup_state():
    """{"running", "result", "last" (epoch seconds or 0), "timer" (enabled?)}."""
    _rc, out, _e = _run("systemctl", "--user", "show", UNIT, "--timestamp=unix",
                        "-p", "ActiveState,Result,ExecMainStatus,ExecMainExitTimestamp", timeout=10)
    st = dict(line.split("=", 1) for line in out.splitlines() if "=" in line)
    ts = st.get("ExecMainExitTimestamp", "").lstrip("@")
    last = int(ts) if ts.isdigit() else 0
    rc, _o, _e = _run("systemctl", "--user", "is-enabled", "--quiet", TIMER, timeout=10)
    return {"running": st.get("ActiveState") in ("activating", "active", "deactivating"),
            "result": st.get("Result", ""), "status": st.get("ExecMainStatus", ""), "last": last,
            "timer": rc == 0}


def backup_timer(on):
    """Turn the daily backup on/off and remember it, so the next `chezmoi update` doesn't turn it back on."""
    store.set("restic_timer_off", not on)
    _run("systemctl", "--user", "daemon-reload", timeout=20)
    return _err(*_run("systemctl", "--user", "enable" if on else "disable", "--now", TIMER,
                      timeout=20)[0::2], "Changing the daily backup")


# --- login shell ---------------------------------------------------------------

def current_shell():
    return pwd.getpwuid(os.getuid()).pw_shell


def shells():
    """[path] of bash/zsh/fish that are listed in /etc/shells and installed (one path per shell)."""
    try:
        listed = [s.strip() for s in open("/etc/shells") if s.strip().startswith("/")]
    except OSError:
        listed = []
    cur = current_shell()
    out, seen = [], set()  # one path per shell: the current one, else /usr/bin/…
    for s in sorted(listed, key=lambda p: (p != cur, not p.startswith("/usr/bin/"), p)):
        name = os.path.basename(s)
        if name in SHELLS and name not in seen and os.access(s, os.X_OK) and not os.path.isdir(s):
            out.append(s)
            seen.add(name)
    return sorted(out, key=lambda p: SHELLS.index(os.path.basename(p)))


def set_shell(path):
    """(True, "") / (False, message) / (None, argv): None = AccountsService is missing (Minimal), run argv in a
    terminal instead (sudo usermod)."""
    if path not in shells():
        return False, "Not a shell from /etc/shells"
    if path == current_shell():
        return True, ""
    user = pwd.getpwuid(os.getuid()).pw_name
    try:
        from gi.repository import Gio, GLib
        bus = Gio.bus_get_sync(Gio.BusType.SYSTEM)
        res = bus.call_sync("org.freedesktop.Accounts", "/org/freedesktop/Accounts", "org.freedesktop.Accounts",
                            "FindUserByName", GLib.Variant("(s)", (user,)), GLib.VariantType("(o)"),
                            Gio.DBusCallFlags.NONE, 10000, None)
        obj = res.unpack()[0]
        bus.call_sync("org.freedesktop.Accounts", obj, "org.freedesktop.Accounts.User", "SetShell",
                      GLib.Variant("(s)", (path,)), None, Gio.DBusCallFlags.ALLOW_INTERACTIVE_AUTHORIZATION,
                      300000, None)  # the polkit prompt waits for the user
    except Exception as e:  # noqa: BLE001 — GLib.Error or no GI: decide below
        msg = getattr(e, "message", str(e))
        if "ServiceUnknown" in msg or "was not provided by any .service" in msg or "No such interface" in msg:
            return None, ["kitty", "--hold", "-e", "sudo", "usermod", "--shell", path, user]
        if "NotAuthorized" in msg or "PermissionDenied" in msg or "Dismissed" in msg or "cancel" in msg.lower():
            return False, "Not changed (not authorised)"
        return False, msg.split(": ", 1)[-1] if msg.startswith("GDBus.Error") else msg
    return True, ""


# --- read-only facts -----------------------------------------------------------

def dotfiles_state():
    """{"source", "remote", "rev", "dirty", "installer"}; "" where unknown."""
    st = {"source": "", "remote": "", "rev": "", "dirty": False, "installer": os.path.isfile(INSTALLER)}
    exe = chezmoi_bin()
    if exe:
        rc, out, _e = _run(exe, "source-path", timeout=10)
        st["source"] = out.strip() if rc == 0 and os.path.isdir(out.strip()) else ""
    src = st["source"]
    if src and shutil.which("git"):
        rc, out, _e = _run("git", "-C", src, "remote", "get-url", "origin", timeout=5)
        remote = display_repository(out.strip()) if rc == 0 else ""
        if remote.startswith("git@"):
            remote = remote[4:].replace(":", "/", 1)
        st["remote"] = re.sub(r"^[a-z+]+://", "", remote).removesuffix(".git")
        rc, out, _e = _run("git", "-C", src, "rev-parse", "--short", "HEAD", timeout=5)
        st["rev"] = out.strip() if rc == 0 else ""
        rc, out, _e = _run("git", "-C", src, "status", "--porcelain", "--untracked-files=no", timeout=5)
        st["dirty"] = rc == 0 and bool(out.strip())
    return st


def installed_state():
    """[(label, value)] of what the installer set up. Each probe is quick and read-only."""
    rows = []
    dm = os.path.realpath("/etc/systemd/system/display-manager.service")
    dm = os.path.basename(dm).removesuffix(".service") if os.path.exists(dm) else ""
    rows.append(("Login", {"gdm": "GDM", "sddm": "SDDM", "greetd": "greetd + tuigreet", "lightdm": "LightDM"}
                 .get(dm, dm or "none (text console)")))
    rc, out, _e = _run("rpm", "-q", "--qf", "%{VENDOR}", "hyprland", timeout=10)
    if rc == 0:
        m = re.search(r"Copr - user (\S+)", out)
        rows.append(("Hyprland", f"from COPR {m.group(1)}" if m else f"from {out.strip() or 'unknown vendor'}"))
    else:
        rows.append(("Hyprland", "not installed as a package"))
    rc, out, _e = _run("flatpak", "remotes", "--user", "--columns=name", timeout=10)
    rows.append(("Flathub", "added (no apps installed by fw13)" if rc == 0 and "flathub" in out.split()
                 else "not added"))
    return rows


def fingerprints():
    """Number of enrolled fingers, or None when fprintd isn't there / no reader."""
    user = pwd.getpwuid(os.getuid()).pw_name
    rc, out, err = _run("fprintd-list", user, timeout=10)
    if rc == 127 or "no devices" in (out + err).lower():
        return None
    return len(re.findall(r"^\s*-\s*#\d+:", out, re.M))


def timeshift_state():
    """"btrfs"/"rsync" + whether Timeshift's own schedule is active, or "" when Timeshift isn't set up."""
    try:
        with open("/etc/timeshift/timeshift.json") as f:
            conf = json.load(f)
    except (OSError, ValueError):
        return ""
    mode = "btrfs" if str(conf.get("btrfs_mode", "")).lower() == "true" else "rsync"
    if not conf.get("backup_device_uuid"):
        return ""
    # Timeshift schedules itself: with a schedule_* flag on it writes /etc/cron.d/timeshift-hourly, run by crond.
    flags = any(str(v).lower() == "true" for k, v in conf.items() if k.startswith("schedule_"))
    rc, _o, _e = _run("systemctl", "is-enabled", "--quiet", "crond.service", timeout=10)
    on = flags and os.path.exists("/etc/cron.d/timeshift-hourly") and rc == 0
    return f"{mode}, {'scheduled' if on else 'not scheduled'}"
