[main]
# Colours: written by fw13.theme
include=~/.config/fw13/theme/fuzzel.ini
font=JetBrains Mono:size=12,Font Awesome 6 Free:size=12
terminal=kitty
layer=overlay
width=40
lines=10
horizontal-pad=20
vertical-pad=14
[border]
radius=0
width=2
