[main]
# Colours and the font: written by fw13.theme
include=~/.config/fw13/theme/fuzzel.ini
terminal=fw-term -e
layer=overlay
width=40
lines=10
horizontal-pad=20
vertical-pad=14
[border]
radius=0
width=2
