hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm app -- waybar")
  hl.exec_cmd("uwsm app -- mako")
  hl.exec_cmd("uwsm app -- hyprpaper")
  hl.exec_cmd("uwsm app -- hypridle")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  -- blueman-applet stays for its pairing agent; its tray icon is off (the bar's bluetooth module replaces it).
  hl.exec_cmd([[gsettings set org.blueman.general plugin-list "['!StatusIcon']" && uwsm app -- blueman-applet]])
  hl.exec_cmd("uwsm app -- fcitx5 -d --replace")
  hl.exec_cmd("uwsm app -- wl-paste --watch cliphist store")
  -- Per-screen workspace ranges + login layout (kitty on the laptop's 1, Chromium on the monitor's 1)
  hl.exec_cmd("uwsm app -- fw-workspaces daemon")
end)
