exec-once = uwsm app -- waybar
exec-once = uwsm app -- mako
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = uwsm app -- blueman-applet
exec-once = uwsm app -- fcitx5 -d --replace
exec-once = uwsm app -- wl-paste --watch cliphist store
