# Written by fw13.theme (Settings → Appearance). Changes here are replaced.
[main]
font=JetBrains Mono:size=12,Font Awesome 6 Free:size=12
[colors]
background=1a1b26f2
text=a9b1d6ff
match=7aa2f7ff
selection=292e42ff
selection-text=c0caf5ff
selection-match=7aa2f7ff
border=7aa2f7ff
