# Written by fw13.theme (Settings → Appearance). Changes here are replaced.
$fw_base = rgba(1a1b26ff)
$fw_inner = rgba(1a1b26cc)
$fw_outer = rgba(7aa2f7ff)
$fw_text = rgba(c0caf5ff)
$fw_check = rgba(9ece6aff)
$fw_fail = rgba(f7768eff)
$fw_clock = rgba(a9b1d6ff)
