# Written by fw13.theme (Settings → Appearance). Changes here are replaced.
background #1a1b26
foreground #a9b1d6
selection_background #292e42
cursor #c0caf5
color0  #15161e
color8  #414868
color1  #f7768e
color9  #ff7a93
color2  #9ece6a
color10 #b9f27c
color3  #e0af68
color11 #ff9e64
color4  #7aa2f7
color12 #7da6ff
color5  #bb9af7
color13 #bb9af7
color6  #7dcfff
color14 #0db9d7
color7  #a9b1d6
color15 #c0caf5
